# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParkOwner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParkOwner

  target 'ParkOwner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParkOwnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ParkOwner-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParkOwner-tvOS

  target 'ParkOwner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# react-native-google-place-picker dependencies

pod 'GooglePlacePicker', '= 2.0.1'
pod 'GooglePlaces', '= 2.0.1'
pod 'GoogleMaps', '= 2.0.1'
